# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-27 06:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_awards_app', '0004_auto_20190526_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='all_projects',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project_awards_app.Project'),
        ),
    ]
